# Generated by Django 6.1.1 on 2026-09-23 09:29

import core.storage
import django.db.models.deletion
import downloads.validators
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Tylko PDF, maksymalnie 10 MB. Ten sam plik jest używany w obu wersjach językowych — nazwę i opis ustawiasz osobno dla każdego języka.', upload_to=core.storage.RandomFilenameUploadTo('downloads/files'), validators=[downloads.validators.validate_pdf_upload], verbose_name='Plik')),
                ('order', models.PositiveIntegerField(default=0, help_text='Mniejsza liczba pokazuje się wyżej na liście.', verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Plik do pobrania',
                'verbose_name_plural': 'Pliki do pobrania',
                'ordering': ['order', 'id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DownloadTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='Widoczna na liście plików do pobrania.', max_length=200, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, help_text='Opcjonalnie, kilka zdań o zawartości pliku. Zwykły tekst, bez formatowania.', verbose_name='Opis')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowany'), ('archived', 'Zarchiwizowany')], default='draft', help_text='Szkic — widoczny tylko w panelu. Opublikowany — widoczny na stronie. Zarchiwizowany — zdjęty ze strony, ale plik zostaje.', max_length=16, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, help_text='Uzupełnia się sama przy pierwszej publikacji.', null=True, verbose_name='Data publikacji')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia zmiana')),
                ('master', parler.fields.TranslationsForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='downloads.download', verbose_name='Plik do pobrania')),
            ],
            options={
                'verbose_name': 'Wersja językowa pliku do pobrania',
                'verbose_name_plural': 'Wersje językowe plików do pobrania',
                'default_permissions': (),
                'indexes': [models.Index(fields=['language_code', 'status'], name='downloads_dltr_public_list')],
                'constraints': [models.UniqueConstraint(fields=('master', 'language_code'), name='downloads_downloadtranslation_unique_language_per_download')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
