# Generated by Django 6.1.1 on 2026-09-20 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('xai', 'xAI (Grok)')], default='anthropic', help_text='Firma, której model językowy generuje treść posta.', max_length=16, verbose_name='Dostawca')),
                ('model_name', models.CharField(help_text='Dokładna nazwa modelu u wybranego dostawcy, np. „claude-sonnet-4-5”. Celowo bez listy do wyboru — dostawcy dodają i zmieniają nazwy modeli częściej, niż wychodzą nowe wersje tego panelu.', max_length=100, verbose_name='Nazwa modelu')),
                ('temperature', models.FloatField(default=0.7, help_text='Od 0 (przewidywalnie) do 2 (kreatywnie). Zalecane 0,5–1.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Temperatura')),
                ('max_output_tokens', models.PositiveIntegerField(default=4000, help_text='Limit długości odpowiedzi modelu. Za niski limit może uciąć treść posta.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maks. tokenów wyjścia')),
            ],
            options={
                'verbose_name': 'Ustawienia AI',
                'verbose_name_plural': 'Ustawienia AI',
            },
        ),
        migrations.CreateModel(
            name='PostGenerator',
            fields=[
            ],
            options={
                'verbose_name': 'Post z AI',
                'verbose_name_plural': 'Post z AI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ai_content.aiprovidersettings',),
        ),
    ]
