# Generated by Django 6.1.1 on 2026-09-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='extra_instructions',
            field=models.TextField(blank=True, default='Pisz jak doświadczony optometrysta — rzeczowo, z autorytetem. Stosuj sprawdzone zasady SEO: jasna struktura nagłówków, odpowiedź na intencję wyszukiwania, zasady E-E-A-T.', help_text='Doklejane do promptu przy każdym generowaniu — persona, ton, wytyczne SEO. Możesz zostawić puste albo zmienić na własne.', verbose_name='Dodatkowe instrukcje dla AI'),
        ),
    ]
