# Generated by Django 6.1.1 on 2026-09-22 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_content', '0002_aiprovidersettings_extra_instructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postgenerator',
            options={'default_permissions': (), 'verbose_name': 'Post z AI', 'verbose_name_plural': 'Post z AI'},
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='temperature',
            field=models.FloatField(default=0.7, help_text='Od 0 (przewidywalnie) do 2 (kreatywnie) — dla Anthropic maksimum to 1. Zalecane 0,5–1.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Temperatura'),
        ),
    ]
