# Generated by Django 6.1.1 on 2026-09-20 15:00

import core.storage
import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='JPG, PNG lub WebP, maksymalnie 5 MB. Zostaw puste, żeby strona korzystała z domyślnego logo.', upload_to=core.storage.RandomFilenameUploadTo('branding/logo'), validators=[core.validators.validate_image_upload], verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Branding strony',
                'verbose_name_plural': 'Branding strony',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], help_text='Zamknięta lista — nowa platforma wymaga zmiany w kodzie.', max_length=16, verbose_name='Platforma')),
                ('url', models.URLField(help_text='Pełny adres profilu, np. „https://www.linkedin.com/in/...".', verbose_name='Adres URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Mniejsza liczba pokazuje się wcześniej na liście.', verbose_name='Kolejność')),
                ('branding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='branding.sitebranding', verbose_name='Branding strony')),
            ],
            options={
                'verbose_name': 'Link social media',
                'verbose_name_plural': 'Linki social media',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('branding', 'platform'), name='branding_sociallink_unique_platform_per_branding')],
            },
        ),
    ]
