# Generated by Django 6.1.1 on 2026-09-19 16:11

import about.models
import about.validators
import core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Niezależne od języka — to samo w obu wersjach.', max_length=200, verbose_name='Imię i nazwisko')),
                ('photo', models.ImageField(blank=True, help_text='JPG, PNG lub WebP, maksymalnie 5 MB. To samo zdjęcie jest używane w obu wersjach językowych — opis zdjęcia (alt) ustawiasz osobno dla każdego języka.', upload_to=about.models.about_photo_upload_to, validators=[core.validators.validate_image_upload], verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Strona „O mnie”',
                'verbose_name_plural': 'Strona „O mnie”',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Np. „European Diploma in Optometry".', max_length=200, verbose_name='Nazwa')),
                ('issuer', models.CharField(max_length=200, verbose_name='Wystawca')),
                ('issued_year', models.PositiveSmallIntegerField(validators=[about.validators.validate_issued_year], verbose_name='Rok wydania')),
                ('image', models.ImageField(blank=True, help_text='Opcjonalne. JPG, PNG lub WebP, maksymalnie 5 MB.', upload_to=about.models.certificate_image_upload_to, validators=[core.validators.validate_image_upload], verbose_name='Skan/zdjęcie certyfikatu')),
                ('order', models.PositiveIntegerField(default=0, help_text='Mniejsza liczba pokazuje się wyżej na liście.', verbose_name='Kolejność')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='about.aboutme', verbose_name='Strona „O mnie”')),
            ],
            options={
                'verbose_name': 'Certyfikat',
                'verbose_name_plural': 'Certyfikaty',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutMeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('headline', models.CharField(help_text='Np. „Optometrysta, właściciel gabinetu".', max_length=200, verbose_name='Nagłówek')),
                ('bio', models.TextField(blank=True, help_text='Formatuj przyciskami na pasku — nie musisz znać HTML-a.', verbose_name='Biografia')),
                ('photo_alt', models.CharField(blank=True, help_text='Co widać na zdjęciu, jednym zdaniem. Czytają to osoby niewidome i wyszukiwarki.', max_length=200, verbose_name='Opis zdjęcia (alt)')),
                ('meta_title', models.CharField(blank=True, help_text='Maksymalnie 60 znaków. Zostaw puste, żeby użyć nagłówka.', max_length=60, verbose_name='Tytuł SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Najlepiej 150–160 znaków. Zostaw puste, żeby użyć nagłówka.', max_length=160, verbose_name='Opis SEO')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowany'), ('archived', 'Zarchiwizowany')], default='draft', help_text='Szkic — widoczny tylko w panelu. Opublikowany — widoczny na stronie. Zarchiwizowany — zdjęty ze strony, ale treść zostaje.', max_length=16, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, help_text='Uzupełnia się sama przy pierwszej publikacji.', null=True, verbose_name='Data publikacji')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia zmiana')),
                ('master', parler.fields.TranslationsForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.aboutme', verbose_name='Strona „O mnie”')),
            ],
            options={
                'verbose_name': 'Wersja językowa strony „O mnie”',
                'verbose_name_plural': 'Wersje językowe strony „O mnie”',
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('master', 'language_code'), name='about_aboutmetranslation_unique_language_per_about')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
