# Generated by Django 6.1.1 on 2026-09-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(help_text='Instytucja albo organizacja, która wydała certyfikat, np. „ECOO".', max_length=200, verbose_name='Wystawca'),
        ),
    ]
