# Generated by Django 6.1.1 on 2026-09-19 11:22

import blog.models
import blog.validators
import django.db.models.deletion
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, help_text='JPG, PNG lub WebP, maksymalnie 5 MB. Ten sam obraz jest używany w obu wersjach językowych — opis obrazu (alt) ustawiasz osobno dla każdego języka.', upload_to=blog.models.post_cover_upload_to, validators=[blog.validators.validate_cover_image], verbose_name='Obraz okładki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posty',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='Widoczny na liście postów i jako nagłówek H1 strony.', max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(blank=True, help_text='Końcówka adresu strony. Zostaw puste — uzupełni się z tytułu. Po opublikowaniu lepiej go nie zmieniać: stary adres przestanie działać.', max_length=220, verbose_name='Adres URL (slug)')),
                ('excerpt', models.CharField(help_text='Dwa–trzy zdania streszczenia. Pokazuje się na liście postów i zastępuje opis SEO, jeśli go nie wypełnisz.', max_length=400, verbose_name='Zajawka')),
                ('content', models.TextField(blank=True, help_text='Formatuj przyciskami na pasku — nie musisz znać HTML-a.', verbose_name='Treść')),
                ('cover_image_alt', models.CharField(blank=True, help_text='Co widać na obrazku, jednym zdaniem. Czytają to osoby niewidome i wyszukiwarki.', max_length=200, verbose_name='Opis obrazu okładki (alt)')),
                ('meta_title', models.CharField(blank=True, help_text='Maksymalnie 60 znaków. Zostaw puste, żeby użyć tytułu posta.', max_length=60, verbose_name='Tytuł SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Najlepiej 150–160 znaków. Zostaw puste, żeby użyć zajawki.', max_length=160, verbose_name='Opis SEO')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowany'), ('archived', 'Zarchiwizowany')], default='draft', help_text='Szkic — widoczny tylko w panelu. Opublikowany — widoczny na stronie. Zarchiwizowany — zdjęty ze strony, ale treść zostaje.', max_length=16, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, help_text='Uzupełnia się sama przy pierwszej publikacji. Zmień tylko, jeśli chcesz pokazać inną datę.', null=True, verbose_name='Data publikacji')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia zmiana')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Wersja językowa posta',
                'verbose_name_plural': 'Wersje językowe postów',
                'default_permissions': (),
                'indexes': [models.Index(fields=['language_code', 'status', '-published_at'], name='blog_posttr_public_list')],
                'constraints': [models.UniqueConstraint(fields=('master', 'language_code'), name='blog_posttranslation_unique_language_per_post'), models.UniqueConstraint(fields=('language_code', 'slug'), name='blog_posttranslation_unique_slug_per_language')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
