# Generated by Django 6.1.1 on 2026-09-19 14:29

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.post', verbose_name='Post'),
        ),
    ]
